name: foodpoint
description: FoodPoint - приложение для поиска кафе и ресторанов
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  dio: ^5.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^15.2.5
  intl: ^0.19.0
  get: ^4.6.5
  provider: ^6.1.5
  google_fonts: ^6.2.1
  url_launcher: ^6.1.7
  animated_text_kit: ^4.2.2
  page_transition: ^2.0.9
  flutter_local_notifications: ^19.2.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.0.14
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7
  file_picker: ^5.2.7
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  retrofit_generator: ^8.2.1
  json_serializable: ^6.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - l10n/

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
