// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRk45u_nVbXzdCFL7erUgO3WRoyW1XAt0',
    appId: '1:347161755157:web:dd78b90963e6d7c62ad81c',
    messagingSenderId: '347161755157',
    projectId: 'foodpoint-lira',
    authDomain: 'foodpoint-lira.firebaseapp.com',
    storageBucket: 'foodpoint-lira.firebasestorage.app',
    measurementId: 'G-W2S5CNKWCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhV4YBIwr5fukjt8G7AsfWM-7lzDfz9Ng',
    appId: '1:347161755157:android:d1b43f78ac6015242ad81c',
    messagingSenderId: '347161755157',
    projectId: 'foodpoint-lira',
    storageBucket: 'foodpoint-lira.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hv-xrInPtFQ5hXV_hS3QK_zKn6jqQFY',
    appId: '1:347161755157:ios:d9c1a47c27bcca112ad81c',
    messagingSenderId: '347161755157',
    projectId: 'foodpoint-lira',
    storageBucket: 'foodpoint-lira.firebasestorage.app',
    iosBundleId: 'com.example.foodpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6hv-xrInPtFQ5hXV_hS3QK_zKn6jqQFY',
    appId: '1:347161755157:ios:d9c1a47c27bcca112ad81c',
    messagingSenderId: '347161755157',
    projectId: 'foodpoint-lira',
    storageBucket: 'foodpoint-lira.firebasestorage.app',
    iosBundleId: 'com.example.foodpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRk45u_nVbXzdCFL7erUgO3WRoyW1XAt0',
    appId: '1:347161755157:web:72ae13c3891762322ad81c',
    messagingSenderId: '347161755157',
    projectId: 'foodpoint-lira',
    authDomain: 'foodpoint-lira.firebaseapp.com',
    storageBucket: 'foodpoint-lira.firebasestorage.app',
    measurementId: 'G-SMZZYJGKYM',
  );

}